### ISSUE TITLE
Error: ETIMEDOUT when opening websockets

### ISSUE THREAD

**Issue by mattheuspirovani** [bmino/binance-triangle-arbitrage#77] opened 2019-07-27 22:45 UTC
**Env:**
Node: 10.15.3
Npm: 6.9.0

**Error:**
```
binance-triangle-arbitrage@5.2.2 start /mnt/d/Develop/binance-triangle-arbitrage
node src/main/Main.js

Successfully pinged the Binance api in 378 ms
Found 533/582 currently trading tickers
Found 229 triangular relationships
Checking configuration ...
Opening 533 depth websockets ...
/mnt/d/Develop/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1835
                            if (err) throw err;
                                     ^

Error: ETIMEDOUT
    at Timeout._onTimeout (/mnt/d/Develop/binance-triangle-arbitrage/node_modules/request/request.js:849:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@5.2.2 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-triangle-arbitrage@5.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mattheus/.npm/_logs/2019-07-27T22_41_50_609Z-debug.log
```

**Config:**
Default, without changes (only API Key of course).

**Comment by bmino** [comment] 2019-07-30 15:04
I've seen this error come up a few times recently in issues, but not recently in running the bot. When I used to encounter it, the main issue was a buried api restriction error that wasn't reported cleanly. Essentially I had started the bot twice+ in quick succession and exhausted the maximum allowed weight for api requests.

Does this happen the first time you run the bot?

**Comment by mattheuspirovani** [comment] 2019-07-31 02:16
Thanks for your reply.

> Does this happen the first time you run the bot?
Yes.

**Comment by bmino** [comment] 2019-08-10 22:11
This is the most pressing issue for this project atm. This appears to be an issue with your local nameserver according to the binance library we use. What operating system are you using?

**Comment by vfelletti** [comment] 2019-08-10 22:20
> This is the most pressing issue for this project atm. This appears to be an issue with your local nameserver according to the binance library we use. What operating system are you using?

I have the same problem, I used Windows 10

**Comment by bmino** [comment] 2019-08-10 22:47
This is the most recent lead:
https://github.com/jaggedsoft/node-binance-api/issues/251

**Comment by cardimajs** [comment] 2019-09-28 14:47
hi, same problem here using arch linux

any fix?

thks.

**Comment by bmino** [comment] 2019-10-08 18:33
Unfortunately I still cannot reproduce this issue to troubleshoot

**Comment by cardimajs** [comment] 2019-10-22 02:44
@bmino  what SO are you using?

**Comment by bmino** [comment] 2019-10-23 03:13
If you mean OS, I use Ubuntu mostly. I have run the app on both macos and windows 10 too

**Comment by cardimajs** [comment] 2019-10-24 05:13
Yes, sorry, i will try using another SO thanks.

**Comment by cardimajs** [comment] 2019-11-02 01:28
I tested using Arch Linux and Windows 10 i get the same problem in both.

![image](https://user-images.githubusercontent.com/5782144/68064164-d8be1100-fcf6-11e9-9935-55716acaac43.png)

can you help?

Thanks.

**Comment by Qwertzi01** [comment] 2020-02-25 14:24
Hi I have still the same problem. Another DNS server already tried. NO solution. 
Any other ideas to fix this problem? The error occurs at different times during runtime.
Environment: Node.js v12.10.0 with current npm version. OS I tried: Windows 8 / Debian 9

**Comment by bmino** [comment] 2020-02-27 00:59
@Qwertzi01 I selected jaggedsoft's implementation because it was vastly superior when I started this project. Since then, quite a few PRs have been merged into the api to accommodate this app.

@cardimajs I am still unable to reproduce locally on linux or in the cloud. Would you share your cpu specs please? Mostly on cpu, cores, and threads

**Comment by cardimajs** [comment] 2020-03-03 04:54
@bmino 

my machine specs is:
Ryzen 7 2700, 8 cores 16 threads
32GB 3200mhz

**Comment by bmino** [comment] 2020-03-03 19:22
@cardimajs thank you, that should be more than sufficient. I have typically been running on machines with 4 cores.

I had a websocket fail to connect yesterday starting the app, and on restarting all was well. A suggestion was made that the ISP was blocking requests, but if so this would be inconsistent.

In running locally, I haven't had any issues beyond that startup fluke when running for a few hours

**Comment by alouest03** [comment] 2020-04-02 17:07
Hello same issue ;(
VM Promox  4 Cores 8 Go Ram Debian 10 at contabo.com

[2020-04-02T16_51_53_338Z-debug.log](https://github.com/bmino/binance-triangle-arbitrage/files/4422432/2020-04-02T16_51_53_338Z-debug.log)

**Comment by gerardoCD** [comment] 2020-07-06 04:50
I have the same problem 
4 nucleos 8 hilos
<img width="910" alt="Captura de Pantalla 2020-07-05 a la(s) 23 49 49" src="https://user-images.githubusercontent.com/25653518/86556923-3e177100-bf1a-11ea-858f-50a9d12fc3fc.png">

**Comment by bmino** [comment] 2020-08-06 15:06
Will somebody experiencing this issue restart the bot with an `INITIALIZATION_INTERVAL` of 1000?
My theory is that binance is timing out your websockets when more than 5 connections are initialized per second. Really strange since this doesn't affect everybody equally

**Comment by bmino** [comment] 2020-08-09 00:00
I have tried to aggressively open websockets concurrently and still have not reproduced this issue. Can somebody experiencing this attempt to start the bot with different api keys? Or on a different IP address?

**Comment by bmino** [comment] 2020-08-09 22:06
Investigating further this appears to be related to a request object timing out (as the error implies). We can increase the allowed period for timeouts by adding the following to BinanceApi.js and restarting the bot. Request timeouts are configured by the `recvWindow` property which defaults to 5000.

```js
const binance = require('node-binance-api')({
    APIKEY: CONFIG.KEYS.API,
    APISECRET: CONFIG.KEYS.SECRET,
    test: !CONFIG.TRADING.ENABLED,
    log: (msg) => logger.binance.info(msg),
    verbose: CONFIG.LOG.VERBOSE,
    recvWindow: 10000 // <--- This right here
});
```

**Comment by bmino** [comment] 2020-08-10 03:17
New config options have been introduced in version 5.5.0!

Starting the bot with `TIMING.USE_SERVER_TIME` set to `true` should fix this issue.
If the `recvWindow` needs to be increased, it can be done via `TIMING.RECEIVE_WINDOW`

**Closed by bmino** 2020-08-10 03:17 UTC
Labels: bug, help wanted
