### ISSUE TITLE
Code places one order and crashes

### ISSUE THREAD

**Issue by georgekhanachat** [bmino/binance-triangle-arbitrage#133] opened 2021-02-05 11:18 UTC
Hey @bmino! 

I just recently cloned your repo, honestly looks pretty neat. I've had the same problem where its not been placing orders even at really high percentages of 4% that have been going own for an age of around 40 to 100 seconds. I have a very similar config file. The logs still show that WebSocket are being disconnected so i increased the bundle size in hopes of reducing the number of sockets but that didn't fix the issue. The program would run on the HUD make a max of one trade and exit with the following error:
![image](https://user-images.githubusercontent.com/58150211/107026869-cddd1080-67c4-11eb-9377-1156bbd65f0f.png)

I hope to reopen this issue to help make this program work!

_Originally posted by @georgekhanachat in https://github.com/bmino/binance-triangle-arbitrage/issues/116#issuecomment-773969331_

**Comment by bmino** [comment] 2021-02-05 16:35
There are a few questions in that issue haha.

1) The bot is configured to stop after one trade by default (`EXECUTION.CAP`). Check out the config readme on how that is configured
2) Orders will only be placed that match your thresholds. This includes age thresholds and profit thresholds. Check out the config readme on how these work.
3) ELIFECYCLE errors will happen when your system can't handle too many requests or a request is blocked. It happens

**Comment by bmino** [comment] 2021-02-05 16:37
Also, I haven't personally found that modifying the websocket bundle size had an affect on disconnecting websockets. That was put in there as a debugging tool before the underlying issue was discovered which was the cpu being overloaded and becoming unable to handle websocket ping/pong packets

**Comment by zadewg** [comment] 2021-02-05 19:38
I believe this might be caused by some limitation on Binance's side. Regardless of configuration I seem to crash after 9 seconds of subscriptions consistently.

This is also the case using most conservative configuration such as DEPTH 5, INTERVAL 1000 (bundle size 1).

**Comment by zadewg** [comment] 2021-02-05 19:52
Funny enough, setting
   
``` json
    "BINANCE_OPTIONS": {
      "recvWdindow": 60000,
      "useServerTime": true
    }
```

 As sugested [here](https://github.com/jaggedsoft/node-binance-api#troubleshooting) allows me to get through the `Opening 315 depth websockets for 315 tickers ...` section but crashes inmediatly after `Waiting for all tickers to receive initial depth snapshot ...` with another Timeout.
 
I have also tried increasing the [receive timeout](https://github.com/bmino/binance-triangle-arbitrage/blob/892f08a26752e8af4c06a3423168af5717698040/src/main/Main.js#L58) with no success. 

Binance must be under heavy load with the recent pump and dump campaigns.

**Comment by bmino** [comment] 2021-02-05 20:17
What do you see in your performance log about cpu cycle usage?

**Comment by zadewg** [comment] 2021-02-05 21:01
> What do you see in your performance log about cpu cycle usage?

No reference to CPU cycle usage, only latency messages (very high btw, about 3600ms)

**Comment by bmino** [comment] 2021-02-05 21:25
The cpu output is configured by default every 2 minutes by the `LOG.STATUS_UPDATE_INTERVAL`

**Comment by bmino** [comment] 2021-02-05 21:28
Pinging will only resolve the url, that is not interacting with the api and getting an api response so it should be faster

**Comment by zadewg** [comment] 2021-02-05 22:09
The cpu output will not be logged because it is configured [after the line 58, where it crashes](https://github.com/bmino/binance-triangle-arbitrage/blob/892f08a26752e8af4c06a3423168af5717698040/src/main/Main.js#L73). I can modify the code to overcome this but im not sure if the ouput will then be relevant to you, let me know.

**Comment by bmino** [comment] 2021-02-05 22:18
Ahh okay, so the bot isn't successfully initializing the depth caches. This means it is failing to either open a websocket, or make the depth cache init request.

**Comment by bmino** [comment] 2021-02-05 22:18
What cpu is this running on?

**Comment by zadewg** [comment] 2021-02-05 22:34
> What cpu is this running on?

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

On Ubuntu 20.04.2 LTS

**Comment by bmino** [comment] 2021-02-05 22:41
I assume you are using the latest version right? In the original screenshot posted, the output implies that the depth caches were already setup successfully and the error occurred during runtime.

Once all startup logic has completed and the depth caches are initialized, there is a "Initialized" log output as the bot is now running calculations

**Comment by Utone** [comment] 2021-02-17 08:41
Binance had upgraded their API, we are not experiencing heavy load related issues since a couple of days.

Curious if running 
`    "BINANCE_OPTIONS": {
      "recvWdindow": 60000,
      "useServerTime": true
    }`
 Now, still gives the same result.

**Comment by bmino** [comment] 2021-02-17 20:19
I am closing this issue as discussion has drifted in many directions from the original issue. Please feel free to open any new specific issues and we can address them individually

**Closed by bmino** 2021-02-17 20:19 UTC
